### PR TITLE
The great ansible migration

### PR DESCRIPTION
**Pull request by mcritchlow**
Hi @ucsdlib/developers -

Ok, here's my pass at an ansible alternative to dams-vagrant. A few things:

Please see the `README.md` file for instructions on getting things setup and provisioned. If anything doesn't make sense there, let me know so we can get it documented as best we can.

1. This is not, necessarily, faster overall than what we had before. Particularly on the initial provision. That said, after that initial provision it should be significantly faster and more reliable as far as updates go.

2. The VM is currently allocated 2G of RAM and 2 CPUs. Otherwise, it's quite slow.. If you need to change this for your own system then of course do what you need to.

3. Please test and let me know if anyone is off or not working. As you can see this is essentially a complete re-write, and I had to make some concessions with some existing bash scripts, like the damsrepo loading scripts, that have very particular expectations as far as the context in which they're run. I may have missed something along the way, and it will help to have as many eyes on this as possible.

Assuming we move forward with this, if anyone would like a rundown later on how this works I'd be happy to do a walkthrough and/or answer questions as they come up. Thanks in advance for testing!

Fixes: #12

### CODE REVIEW

**Comment by lsitu** [comment]
@mcritchlow It looks like something is wrong with the URL https://atlas.hashicorp.com/ubuntu/xenial64. I got "Error: The requested URL returned error: 404 Not Found":

Bringing machine 'lib-damspas' up with 'virtualbox' provider...
==> lib-damspas: Box 'ubuntu/xenial64' could not be found. Attempting to find and install...
    lib-damspas: Box Provider: virtualbox
    lib-damspas: Box Version: >= 0
The box 'ubuntu/xenial64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/xenial64"]
Error: The requested URL returned error: 404 Not Found
make: *** [up] Error 1

**Comment by mcritchlow** [comment]
@lsitu - well that's strange.. I've certainly not run into that before. I wonder if they're having an issue with their site at the moment. That's unfortunate..

**Comment by lsitu** [comment]
@mcritchlow It could be and I see the site is not responding at that time, and now it's 404.

**Comment by hweng** [comment]
@mcritchlow LGTM:+1:

**Comment by mcritchlow** [comment]
@ucsdlib/developers - I've updated the README in 079e94881d352bbe809a6d9756679a38bd22362d to clarify minimum recommended versions of the required software. Thanks for catching that!

**Comment by lsitu** [comment]
👍

**Pull request merged**
