### PR TITLE
Added user group dams-editor and remove dams-rci group. DM-186

### PR DESCRIPTION
**Pull request by lsitu**
https://lib-jira.ucsd.edu:8443/browse/DM-186

### CODE REVIEW

**Comment by mcritchlow** [comment]
👍

**Comment by lsitu** [comment]
@ucsdlib/developers Please review, comments... Thanks.

**Comment by VivianChu** [comment]
👍

**Comment by hweng** [comment]
:+1:

**Comment by lsitu** [comment]
Thank you all for the reviewing.

**Pull request merged**
