### PR TITLE
adding phantomjs and removing extraneous configuration script copying

### PR DESCRIPTION
**Pull request by mcritchlow**

### CODE REVIEW

**Comment by mcritchlow** [comment]
@ucsdlib/developers please take a look and run this update when you have a chance locally

**Comment by VivianChu** [comment]
👍

**Comment by lsitu** [comment]
:+1:

**Comment by mcritchlow** [comment]
Just noting that, as shown in the Vagrantfile change, there is a new LTS version of Ubuntu. As a separate step/PR, I'll look into how easily we can upgrade the VM to use that.

**Comment by hweng** [comment]
👍

**Comment by mcritchlow** [comment]
@ucsdlib/developers thanks for taking a look and testing. could someone please merge at your convenience?

**Comment by lsitu** [comment]
Done.

**Pull request merged**
